import numpy as np


def func_G(L2, L3, g, m2, m3, q2, q3):
    """
    %FUNC_G
    %    G = FUNC_G(L2,L3,G,M2,M3,Q2,Q3)

    %    This function was generated by the Symbolic Math Toolbox version 8.1.
    %    12-Feb-2026 09:55:36
    """
    t2 = np.cos(q2)
    t3 = q2 + q3
    t4 = np.cos(t3)
    G1 = 0.0
    G2 = g * m3 * (L2 * t2 + L3 * t4 * (1.0 / 2.0)) + L2 * g * m2 * t2 * (1.0 / 2.0)
    G3 = L3 * g * m3 * t4 * (1.0 / 2.0)
    G = np.array([[G1], [G2], [G3]])
    return G