import numpy as np


def func_M(I2x, I3x, I2y, I3y, I1z, I2z, I3z, L2, L3, m2, m3, q2, q3):
    """
    %FUNC_M
    %    M = FUNC_M(I2X,I3X,I2Y,I3Y,I1Z,I2Z,I3Z,L2,L3,M2,M3,Q2,Q3)

    %    This function was generated by the Symbolic Math Toolbox version 8.1.
    %    12-Feb-2026 09:55:35
    """
    t2 = q2 * 2.0
    t3 = q3 * 2.0
    t4 = t2 + t3
    t5 = np.cos(t4)
    t6 = L2 ** 2
    t7 = np.cos(t2)
    t8 = L3 ** 2
    t9 = np.cos(q3)
    t10 = m3 * t8 * (1.0 / 4.0)
    t11 = L2 * L3 * m3 * t9 * (1.0 / 2.0)
    t12 = I3y + t10 + t11
    M11 = I2x * (1.0 / 2.0) + I3x * (1.0 / 2.0) + I1z + I2z * (1.0 / 2.0) + I3z * (1.0 / 2.0) + t11 + I3x * t5 * (
                1.0 / 2.0) + I2x * t7 * (1.0 / 2.0) - I3z * t5 * (1.0 / 2.0) - I2z * t7 * (1.0 / 2.0) + m2 * t6 * (
                      1.0 / 8.0) + m3 * t6 * (1.0 / 2.0) + m3 * t8 * (1.0 / 8.0) + m2 * t6 * t7 * (
                      1.0 / 8.0) + m3 * t5 * t8 * (1.0 / 8.0) + m3 * t6 * t7 * (1.0 / 2.0) + L2 * L3 * m3 * np.cos(
        q3 + t2) * (1.0 / 2.0)
    M12 = 0.0
    M13 = 0.0
    M21 = 0.0
    M22 = I2y + I3y + t10 + m2 * t6 * (1.0 / 4.0) + m3 * t6 + L2 * L3 * m3 * t9
    M23 = t12
    M31 = 0.0
    M32 = t12
    M33 = I3y + t10
    M = np.array([[M11, M12, M13],
                  [M21, M22, M23],
                  [M31, M32, M33]])
    return M
